site_name: retnikt
theme:
  name: null
  custom_dir: 'mkdocs-material/material'
  language: en
  palette:
    primary: 'blue'
    accent: 'blue'
  font:
    text: 'Noto Sans'
    code: 'Fira Code'
  logo:
    icon: 'developer_board'
  feature: false
  favicon: 'assets/images/favicon2.png'
copyright: '© retnikt 2019'
